version: '3.5'
services:
  db-herois:
    image: postgres
    volumes:
      - postgres_backup:/var/lib/postgresql/data/
    networks:
      - proxy
    env_file:
      - ./env_files/.env.prod.db

  api-herois:
    container_name: api-herois
    build: ./api
    restart: always
    command: uwsgi --ini uwsgi.ini
    volumes:
      - api_data:/docker_api
    networks:
      - proxy
    env_file:
      - ./env_files/.env.dev.web
    depends_on:
      - db-herois

  nginx-herois:
    container_name: nginx-herois
    build: ./nginx
    restart: always
    volumes:
      - api_data:/docker_api
      - ./log:/var/log/nginx
    networks:
      - proxy
    depends_on:
      - api-herois
    env_file:
      - ./env_files/.env.prod.nginx


volumes:
  postgres_backup:
    driver: local
    driver_opts:
      type: none
      device: $PWD/volumes/postgres_backup
      o: bind

networks:
  proxy:
    external:
      name: nginx-proxy