# Generated by Django 3.1.7 on 2021-03-24 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('herois', '0002_auto_20210323_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heroi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herois.heroi')),
            ],
            options={
                'verbose_name': 'Herói favorito',
                'verbose_name_plural': 'Herói favorito',
            },
        ),
    ]
